requires 'JSON', '>= 2.0';
requires 'JSON::XS', '>= 2.0';
requires 'LWP::UserAgent::Determined';
requires 'IO::Socket::SSL';
requires 'File::MMagic';
requires 'XML::XPath';
requires 'XML::LibXML';
build_requires 'Apache::TestMM';
test_requires 'Image::Magick', '<7';
test_requires 'Apache::TestRunPerl';
test_requires 'Devel::Cover';
