%global debug_package %{nil} # Don't generate debug info
%define perl_lib /opt/grnoc/venv/
%define specfile_deps %(cat cpanfile | sed -r 's/^requires ([^[:space:]]*)/Requires: perl(\\1)/' | sed 's/["'"'"';]//g')
Name:           perl-GRNOC-WebService-Client
Version:        1.5.4
Release:        1%{?dist}
Summary:        GRNOC::WebService::Client Perl module
License:        GRNOC
Group:          Development/Libraries
URL:            http://globalnoc.iu.edu
Source0:        GRNOC-WebService-Client-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
%if 0%{rhel} == 8
BuildArch: x86_64
%else
BuildArch: noarch
%endif
Requires:       perl >= 5.8.8
%if 0%{?rhel} == 7
%{specfile_deps}
%endif
BuildRequires:  mod_perl
BuildRequires:  mod_perl-devel
BuildRequires:  httpd-devel
BuildRequires:  ImageMagick-devel
BuildRequires:  perl-GRNOC-WebService >= 1.2.5
Requires:       perl-GRNOC-Config >= 1.0.7

%if 0%{?el7}
Requires:       perl-LWP-Protocol-https
%endif

%description
WebService Client Module

%prep
%setup -q -n GRNOC-WebService-Client-%{version}

%build
%{__perl} Makefile.PL
make dist

%install
%if 0%{rhel} == 8
%{__install} -d -p %{buildroot}%{perl_lib}%{name}/lib/perl5
cp -r venv/lib/perl5/* -t %{buildroot}%{perl_lib}%{name}/lib/perl5
%endif

%{__install} -d -p %{buildroot}%{perl_sitelib}/GRNOC/WebService/
%{__install} -d -p %{buildroot}%{perl_sitelib}/GRNOC/WebService/Client/
%{__install} -d -p %{buildroot}/usr/bin/globalnoc/webservice/
%{__install} -d -p %{buildroot}/etc/grnoc/webservice_client/

%{__install} lib/GRNOC/WebService/Client.pm %{buildroot}%{perl_sitelib}/GRNOC/WebService/
%{__install} lib/GRNOC/WebService/Client/Paginator.pm %{buildroot}%{perl_sitelib}/GRNOC/WebService/Client/
%{__install} bin/wsutil.pl %{buildroot}/usr/bin/globalnoc/webservice/
%{__install} conf/config.xml %{buildroot}/etc/grnoc/webservice_client/config.xml

%clean
rm -rf $RPM_BUILD_ROOT

%post

if [ ! -e /usr/bin/wsutil ]
  then
    ln -s /usr/bin/globalnoc/webservice/wsutil.pl /usr/bin/wsutil
fi

%files
%if %{rhel} == 8
%{perl_lib}/%{name}/lib/perl5/*
%endif
%defattr(-,root,root,-)
%{perl_sitelib}/GRNOC/WebService/Client.pm
%{perl_sitelib}/GRNOC/WebService/Client/Paginator.pm
/usr/bin/globalnoc/webservice/wsutil.pl
%config(noreplace) /etc/grnoc/webservice_client/config.xml
%changelog
* Mon Jun 13 2011 mrmccrac 1.1.0-1
- Specfile autogenerated by cpanspec 1.77.
